entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

log:
  level: "DEBUG"

providers:
  kubernetesGateway: {}

certificatesResolvers:
  myresolver:
    acme:
      email: "rdg27@pitt.edu"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
